### PR TITLE
initialize webdriver with chrome options 

### PR DESCRIPTION
**Pull request by isarns**

### CODE REVIEW

**Comment by MarketingPip** [comment]
@isarns can you provide a screenshot or log error with chrome add-ons (original template) not working correctly? Is seems things were working on my side before (using window sizes etc in Chrome). Can you ensure the flags you were using - were correct for the Driver version you chose?

**Comment by isarns** [comment]
Setting options to be:
` options = [
            # Define window size here
            "window-size=0,0",
            "ignore-certificate-errors"
            #"headless",
            #"--disable-gpu",
            #"--window-size=1920,1200",
            #"--ignore-certificate-errors",
            #"--disable-extensions",
            #"--no-sandbox",
            #"--disable-dev-shm-usage",
            #'--remote-debugging-port=9222'
        ]`
running the program with 
`self.driver = webdriver.Chrome()` like in your master
Result:
image
Default resolution....

running the program with 
`self.driver = webdriver.Chrome(options = chrome_options)` 
Result:
image
Small window like the options stated.

**Comment by MarketingPip** [comment]
@isarns  - running your changes on a GitHub action. I keep getting 
`selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 10.000`

Can you confirm you aren't getting this message using your changes? (I am trying to re-produce a screenshot like your comment above)

**Comment by isarns** [comment]
Im not getting that error. 
Can you try connecting to some random site that doesn't need authentication? 
E.g. https://google.com

P.s you can just add it in the readme as a note

**Comment by MarketingPip** [comment]
> Im not getting that error. Can you try connecting to some random site that doesn't need authentication? E.g. https://google.com
> 
> P.s you can just add it in the readme as a note

I forgot to mention - try taking a SCREENSHOT with your options via GitHub Action. To verify / see they are working. As it won't properly work. ie - (the options are not properly being added with your changes when ran on GitHub Actions).

**Comment by MarketingPip** [comment]
@isarns - as well can you confirm too your sizes etc you are using for PyVirtualDisplay. As the sizes / options I have set up - you can not see the tab sections of Chrome etc when viewing the driver using PyVirtualDisplay. Only way you can currently change the height of window size - is via PyVirtualDisplay. But all the other option's / flags seem to be passed & working normally. 

If you can add any input / testing feedback to this - would be more than appreciated.  

I would rather know I am wrong & than not having this working properly for everyone out of the box as it's supposed to!

**Comment by MarketingPip** [comment]
Hey @isarns  - just did some more testing on my end you were right! And I was wrong! Your code is working perfect as expected. Thank you for adding this commit! And wishing you an awesome week ahead!  :clinking_glasses:

**Pull request merged**
